### ISSUE TITLE
Incorrect Output

### ISSUE THREAD

**Issue by gawaksh007** [Shivampanwar/Dog-breed-identification#1]
@Shivampanwar I tried using a picture of quite a famous dog in my vicinty. **_Instead of showing the output as Shubham Balodi Breed, it showed an error._** Please train your data again such that this descrepency should not be reflected in future tests. I consider you a person of great machine learning skills, please don't be a reference for disappointment by such results.

**Comment by Shivampanwar** [comment]
Collecting data to take care of your disappointment.
